baseURL: 'https://cjcodes.com/'
languageCode: en-us
title: cjcodes
theme: PaperMod
disqusShortname: cjcodes-com
googleAnalytics: G-582DHX9VVT
enableGitInfo: true
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
    - identifier: manager-docs
      name: manager docs
      url: /manager-docs/

params:
  hideSummary: true
  dateFormat: 2006-01-02
  ShowBreadCrumbs: true
  hideFooter: true
  mainSections:


  socialIcons:
    - name: linkedin
      url: 'https://linkedin.com/in/cjcodes'
    - name: twitter
      url: 'https://twitter.com/cjcodes'

  homeInfoParams:
    Title: ''
    Content: >
      aka. chris johnson

      ===

      - software engineer turned manager
      &nbsp;&nbsp;[twilio](https://twilio.com)

      - technical strategist &nbsp;&nbsp;[whole whale](https://wholewhale.com)

      - founding cto &nbsp;&nbsp;[crisis text line](https://crisistextline.org)
