baseURL: 'https://cjcodes.com/'
languageCode: en-us
title: cjcodes
theme: PaperMod
disqusShortname: cjcodes-com
googleAnalytics: UA-206126234-1
enableGitInfo: true
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true

menu:
  main:
    - identifier: github
      name: questions + requests
      url: https://github.com/cjcodes/cjcodes.com/issues
      weight: -300
    - identifier: posts
      name: posts
      url: /posts/
      weight: -200
    - identifier: manager-docs
      name: manager docs
      url: /manager-docs/
      weight: -100

params:
  hideSummary: true
  dateFormat: 2006-01-02
  ShowBreadCrumbs: true
  hideFooter: true
  mainSections:


  socialIcons:
    - name: linkedin
      url: 'https://linkedin.com/in/cjcodes'

  homeInfoParams:
    Title: ''
    Content: >
      aka. chris johnson

      ===

      - software engineer turned manager
      &nbsp;&nbsp;[twilio](https://twilio.com)

      - technical strategist &nbsp;&nbsp;[whole whale](https://wholewhale.com)

      - founding cto &nbsp;&nbsp;[crisis text line](https://crisistextline.org)
      
      - lead drupal dev + manager &nbsp;&nbsp;[dosomething.org](https://dosomething.org)
